#!/bin/bash
# this batch shell can execute shell script
# on multiple hosts specified by ip list file

user_name="root"
user_pass="111111"

if [ $# != 2 ]; then
    echo "need ip list file and shell file."
    exit
fi
ip_list_file=$1
shell_script=`cat $2`
echo $shell_script
# first invoke free_python.py to setup passphraseless ssh to
# all hosts in ip list file 

#`./free_login.py ${ip_list_file} ${user_name} ${user_pass}`

for i in $(cat ${ip_list_file})
do 
    remote_host="${user_name}@$i"
    echo ${remote_host}
    ssh ${remote_host} "${shell_script}"
    echo "execute shell script on ${remote_host}"
done
