#!/bin/bash
# this shell runs on control node

user_name="root"
user_pass="111111"

root_dir="${HOME}/mbj/CloudIndex"
etc_dir="${root_dir}/etc"

torus_ip_list="${etc_dir}/torus_ip_list"
if [ ! -f "$torus_ip_list" ]; then
    exec "${etc_dir}/download-torus-ip-list"
    wait
fi

# invoke free_python.py to setup passphraseless ssh to
# all torus nodes in torus_ip_list
$( ${etc_dir}/free_login.py ${torus_ip_list} ${user_name} ${user_pass} )
