#!/bin/bash
# automatic create  new instance 
# in openstack cloud platform

export OS_TENANT_NAME=benjin
export OS_USERNAME=benjin
export OS_PASSWORD=benjin
export OS_AUTH_URL="http://localhost:5000/v2.0/"
export SERVICE_ENDPOINT="http://localhost:35357/v2.0"
export SERVICE_TOKEN=benjin

if [ $# = 0 ]; then
    echo "need arguments"
    exit
fi

COMMAND=$1
IP_REG='\([0-9]\{1,3\}\.\)\{3\}[0-9]\{1,3\}'
control_node="control-node"

if [ "$COMMAND" = "boot" ]; then
    # get instance num to be created
    x='arg'
    if [ "$x$2" = "$x" ]; then
        echo "need boot instance num."
        exit 1
    else 
        num=$2
    fi

    for((i=0;i<$num;++i))
    do
        cur_date=`date +%Y%m%d%H%M%S`
        nova boot --flavor=11 --image=37d33b64-fa8d-45ff-989f-475f7e117171 $cur_date
    done
elif [ "$COMMAND" = "boot-control-node" ]; then
    # bind floating ip for control node
    float_ip=`nova list | grep -o "$IP_REG, $IP_REG"`
    if [ "$float_ip" = "" ]; then
        nova boot --flavor=1 --image=37d33b64-fa8d-45ff-989f-475f7e117171 $control_node
        sleep 3s
        floating_ip=`nova floating-ip-list | grep -o "$IP_REG" `
        nova add-floating-ip $control_node $floating_ip 
    else
        echo "control_node already created."
        exit 1
    fi
elif [ "$COMMAND" = "torus-ip-list" ]; then
    nova list | grep -o "=$IP_REG " | grep -o "$IP_REG"
else
    nova $*
fi
