#!/bin/bash
# this shell runs on control node

root_dir=${HOME}/mbj/CloudIndex
etc_dir=${root_dir}/etc

host_prefix="root@"
remote_shell="${etc_dir}/torus-node-deamon $@"
torus_ip_list="${etc_dir}/torus_ip_list"

for i in $(cat ${torus_ip_list})
do 
    remote_host="${host_prefix}$i"
    ssh ${remote_host} "${remote_shell} $i"
done
