#!/bin/bash

local_dir=${HOME}/Programming/C/CloudIndex
# be careful! when change upload dir
upload_dir=/home/iir/mbj
remote_shell="rm ${upload_dir}/* -rf"
host_prefix="iir@"

function clean_remote_dir()
{
    for i in $(cat torus-nodes)
    do 
        remote_host="${host_prefix}$i"
        ssh ${remote_host} "${remote_shell}"
        echo "clean up directory ${remote_host}:${upload_dir}"
    done
}

function copy_it()
{
    for i in $(cat torus-nodes)
    do 
        remote_host="${host_prefix}$i"
        scp -r -q ${local_dir} ${remote_host}:${upload_dir}
        echo "copy to ${remote_host}"
    done
}

if [ $# = 0 ]; then
    clean_remote_dir
    copy_it
fi

COMMAND=$1

if [ "$COMMAND" = "clean" ]; then
    clean_remote_dir
elif [ "$COMMAND" = "copy" ]; then
    copy_it
fi


